platform :ios, '11.0'
use_frameworks!

target 'HoloflowsKit_Example' do
  pod 'HoloflowsKit', :path => '../', :testspecs => ['Tests']

  target 'HoloflowsKit_Tests' do
    inherit! :search_paths

    
  end
end
