platform :ios, '11.0'
use_frameworks!

target 'HoloflowsKit_Example' do
  pod 'HoloflowsKit', :path => '../', :testspecs => ['Tests']

  target 'HoloflowsKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['ConsolePrint'].include? target.name
          target.build_configurations.each do |config|
              if config.name == "Debug"
                  config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] += "ConsolePrint"
              end
          end
      end
  end
end